name: CI
on:
  push:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Install Julia dependencies
        run: julia -e 'import Pkg; Pkg.add("SDDP");Pkg.add("HiGHS");Pkg.add("Clp");Pkg.add("JuMP");Pkg.add("Base");Pkg.add("Xpress");Pkg.add("PythonCall")'  

      - name: Test
        run: |
          pytest

      - name: Check typing
        run: |
          python -m mypy src



